version: '3.8'

services:
  # Development overrides for backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=debug
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev

  # Development overrides for agents
  agents:
    build:
      context: ./agents
      dockerfile: Dockerfile.dev
    environment:
      - LOG_LEVEL=DEBUG
    volumes:
      - ./agents:/app
    command: python -m agents.dev

  # Development overrides for frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    environment:
      - NEXT_PUBLIC_ENABLE_DEBUG=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev

  # Development database with exposed ports and debug settings
  postgres:
    environment:
      - POSTGRES_LOG_STATEMENT=all
      - POSTGRES_LOG_MIN_DURATION_STATEMENT=0
    ports:
      - "5432:5432"

  # Development Redis with debug settings
  redis:
    command: redis-server --loglevel debug
    ports:
      - "6379:6379"